### ISSUE TITLE
It appears the Client does not handle redirects

### ISSUE THREAD

**Issue by NotReallyACat** [theripper93/fvtt-player-client#6] opened 2023-08-18 23:33 UTC
I am running multiple foundry instances on my network so have set up a no-ip ddns service which has seperate host names for each of the instances. This issue I am having is when connecting via the host names it redirects to actual IP+port number which causes the client to white screen.

**Comment by NotReallyACat** [comment] 2023-09-08 14:54
@theripper93 any updates for this?

**Comment by theripper93** [comment] 2023-09-08 14:56
@OmegaRogue is doing quite a lot of work on the client lately, maybe he already knows what's going on

**Comment by OmegaRogue** [comment] 2023-09-08 14:58
I'm not sure what the cause of this could be, reverse proxies definetly work

**Comment by theripper93** [comment] 2023-09-08 15:08
The issue seems to affect mostly the login required by some forge servers

**Comment by OmegaRogue** [comment] 2023-09-08 15:10
I don't have access to any forge instances, so I can't really look for the problem myself in that case

**Comment by theripper93** [comment] 2023-09-08 15:18
i belive you ca njust use the forge home page and attempt to login

**Comment by OmegaRogue** [comment] 2023-09-08 15:26
At which point does the issue occur? After the login?

**Comment by theripper93** [comment] 2023-09-08 15:30
I think when you attempt to click stuff like the "Log in with Google" \ "Log in with Patreon" it will simply go to a blank screen

**Comment by OmegaRogue** [comment] 2023-09-08 15:34
![image](https://github.com/theripper93/fvtt-player-client/assets/24958536/0358bcea-8b76-4b7d-87a0-84c28c3f6815)
Doesn't seem to happen for me, but I'm running the latest version of my fork pre typescript  (1.3.5)

**Comment by theripper93** [comment] 2023-09-08 15:48
I can confirm it's working on my end as well, it might have been an electron bug fixed with some update

**Comment by theripper93** [comment] 2023-09-08 15:50
Fixed in latest

**Closed as completed by theripper93** 2023-09-08 15:50 UTC
Labels: bug
